config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: "pages#home"

  get '/dashboard', to: 'pages#dashboard'

  get '/chatrooms', to: 'pages#chatrooms'

  get '/notifications', to: 'pages#notifications'

  devise_scope :user do
    get '/users/profile', to: 'users/sessions#show', as: 'user_profile'
    get '/users/:id/edit', to: 'users/sessions#edit', as: 'edit_user'
    patch '/users/:id/edit', to: 'users/sessions#update', as: 'update_user'
    get '/users/:id/profile', to: 'users/sessions#show', as: 'profile'
  end

  get 'runs/map', to: "runs#map", as: :map

  resources :runs do
    resources :attendances, only: %i[new create]
    resources :messages, only: :create
    member do
      get 'chatroom', to: "runs#chatroom"
    end
  end

  resources :attendances, only: %i[index show update destroy] do
    resources :reviews, only: %i[new create] # routes Reviews
    member do
      patch 'confirm', to: "attendances#confirm"
      patch 'decline', to: "attendances#decline"
    end
  end
end

app/views/shared/_banner.html.erb
<div class="banner navbar fixed-top" data-controller="notifications-subscription" data-notifications-subscription-user-id-value="<%= current_user.id if user_signed_in? %>">
  <div class="container px-4 pt-2 d-flex align-items-center justify-content-start">
    <%= link_to root_path do %>
      <%= image_tag "new_logo.png", alt:"Runmate", class: "img"%>
    <% end %>
    <%= link_to notifications_path, class:"notification-link ms-auto p-2 d-flex" do %>
      <i class="notification-bell fa-regular fa-bell" data-notifications-subscription-target="bell"></i>
      <% if user_signed_in? %>
        <div class="pastille <%= "d-none" if current_user.unread_notifications_count == 0 %>" data-notifications-subscription-target="pastille">
          <% if current_user.unread_notifications_count > 9 %>
            <%= "9+" %>
          <% else %>
            <%= current_user.unread_notifications_count %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<%# Bottom navigation %>
<div id="navbar-list" data-controller="active-navbar">
  <div class="row">
    <div class="col">
      <% if current_page?(runs_path) %>
        <%= link_to runs_path, class:"link-bottom active" do %>
          <i class="fa-solid fa-house"></i>
        <% end %>
      <% else %>
        <%= link_to runs_path, class:"link-bottom" do %>
          <i class="fa-solid fa-house"></i>
        <% end %>
      <% end %>
    </div>
    <div class="col">
      <% if current_page?(new_run_path) %>
        <%= link_to new_run_path, class:"link-bottom active" do %>
          <i class="fa-solid fa-circle-plus"></i>
        <% end %>
      <% else %>
        <%= link_to new_run_path, class:"link-bottom" do %>
          <i class="fa-solid fa-circle-plus"></i>
        <% end %>
      <% end %>
    </div>
    <div class="col" data-controller="message-notifications-subscription" data-message-notifications-subscription-user-id-value="<%= current_user.id if user_signed_in? %>">
      <div class="chatroom">
        <% if user_signed_in? %>
          <div class="pastille <%= "d-none" if current_user.unread_messages_count == 0 %>" data-message-notifications-subscription-target="pastillemessages">
            <% if current_user.unread_messages_count > 9 %>
              <%= "9+" %>
            <% else %>
              <%= current_user.unread_messages_count %>
            <% end %>
          </div>
        <% end %>
        <% if current_page?(chatrooms_path) %>
          <%= link_to chatrooms_path, class:"link-bottom active" do %>
            <i class="fa-solid fa-message"></i>
          <% end %>
          <% else %>
          <%= link_to chatrooms_path, class:"link-bottom" do %>
            <i class="fa-solid fa-message"></i>
          <% end %>
        <% end %>
      </div>
    </div>
     <div class="col">
      <button class="bg-transparent border-0 p-0 link-bottom" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight">
        <i class="fa-solid fa-ellipsis"></i>
      </button>
    </div>
  </div>
</div>

<%# Side navigation %>
<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel" data-bs-backdrop="false">
  <div class="offcanvas-header">
    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    <div >
      <% if user_signed_in? %>
        <%= link_to user_profile_path, class:"text-decoration-none d-flex flex-end align-items-center" do %>
        <%= cl_image_tag current_user.photo.key, class: "avatar me-3" %>
        <h5 class="m-0 pe-3" id="offcanvasRightLabel"><%= current_user.first_name %></h5>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="d-flex flex-column ps-4 mt-5" id="offcanvasMenu">
    <%= link_to "My Requests", attendances_path  %>
    <%= link_to "My Runs", dashboard_path %>
    <% if user_signed_in? %>
      <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete} %>
    <% else %>
      <%= link_to "Log in", user_session_path %>
    <% end %>
    <%= link_to "Contacts", attendances_path  %>
    <%= link_to "Help", attendances_path  %>
  </div>
</div>