config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: "pages#home"

  get '/dashboard', to: 'pages#dashboard'

  get '/chatrooms', to: 'pages#chatrooms'

  get '/notifications', to: 'pages#notifications'

  devise_scope :user do
    get '/users/profile', to: 'users/sessions#show', as: 'user_profile'
    get '/users/:id/edit', to: 'users/sessions#edit', as: 'edit_user'
    patch '/users/:id/edit', to: 'users/sessions#update', as: 'update_user'
    get '/users/:id/profile', to: 'users/sessions#show', as: 'profile'
  end

  get 'runs/map', to: "runs#map", as: :map

  resources :runs do
    resources :attendances, only: %i[new create]
    resources :messages, only: :create
    member do
      get 'chatroom', to: "runs#chatroom"
    end
  end

  resources :attendances, only: %i[index show update destroy] do
    resources :reviews, only: %i[new create] # routes Reviews
    member do
      patch 'confirm', to: "attendances#confirm"
      patch 'decline', to: "attendances#decline"
    end
  end
end

app/views/pages/_chatroom_card.html.erb
<div class="chatroom-card mb-3">
  <%= link_to "", chatroom_run_path(attendance.run), class:"chatroom-card-link" %>
  <% if attendance.run.photo.attached? %>
    <%= cl_image_tag attendance.run.photo.key, class: ""%>
  <% else %>
    <%= image_tag "cover.png", alt:"Runmate", class: ""%>
  <% end %>
  <div class="chatroom-card-info">
    <h5>#<%= attendance.run.name %></h5>
    <p><%= pluralize(attendance.run.messages.count, 'Message') %></p>
  </div>
</div>

app/views/pages/_notification_card.html.erb
<% case %>
<% when notification.attendance.status == "confirmed" %>
  <div class="notification notification-confirmed <%= "notification-old" if notification.read %>">
    <%= link_to run_path(notification.attendance.run),class:"notification-link" do %>
      <div class="notification-information d-flex align-items-center">
        <i class="notification-icone fa-solid fa-circle-check"></i>
        <span class="notification-info" > Yeah! Your request for <strong> <%= notification.attendance.run.name %> </strong> has been acceped.</span>
      </div>
    <% end %>
  </div>

<% when notification.attendance.status == "declined" %>
  <div class="notification notification-declined <%= "notification-old" if notification.read %>">
    <%= link_to run_path(notification.attendance.run),class:"notification-link" do %>
      <div class="notification-information d-flex align-items-center">
        <i class="notification-icone fa-regular fa-circle-xmark"></i>
        <span class="notification-info" > Sorry! Your request for <strong> <%= notification.attendance.run.name %> </strong> has been declined.</span>
      </div>
    <% end %>
  </div>

<% when notification.attendance.status == "pending" %>
  <div class="notification notification-pending <%= "notification-old" if notification.read %>">
    <%= link_to dashboard_path, class:"notification-link" do %>
      <div class="notification-information d-flex align-items-center">
        <i class="notification-icone fa-solid fa-user"></i>
        <span class="notification-info" ><%= notification.attendance.user.username %> requested to join your run : <strong><%= notification.attendance.run.name %></strong></span>
      </div>
    <% end %>
  </div>
<% end %>

app/views/pages/chatrooms.html.erb
<div class="container my-4", style="padding-top: 60px">
  <%= link_to :back, class:"text-decoration-none ps-1" do %>
    <span class="btn-back fs-6"><i class="fa-solid fa-circle-arrow-left fs-6 btn-back-blue me-1"></i>BACK</span>
  <% end %>
  <h2 class="title-dashboard text-center mb-2">Messages</h2>
  <div class="container p-3 mb-5">
    <% if @attendances.present? %>
      <% @attendances.each do |attendance| %>
          <%= render "chatroom_card", attendance: attendance %>
        <% end %>
      <% else %>
        <p>You haven't joined any run yet!</p>
      <% end %>
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="dashboard-body">
  <div class="container mt-2 mb-4", style="padding-top: 60px">
      <div class="d-flex justify-content-between">
        <%= link_to :back, class:"text-decoration-none" do %>
          <span class="btn-back"><i class="fa-solid fa-circle-arrow-left fs-5 btn-back-blue me-1"></i>BACK</span>
        <% end %>
        <%# Button create new run %>
          <%= link_to new_run_path, class: "new-run-dashboard" do %>
            <i class="fa-solid fa-circle-plus me-2 fs-5"></i>
            <p class="btn-more">NEW RUN</p>
          <% end %>
      </div>
      <h1 class="title-dashboard mt-3 mb-4 text-center">RUNS YOU CREATED</h1>



    <%# <div id="tabContainer" class="container"> %>
      <ul class="nav nav-pills" id="dashboardTab">
        <li class="nav-item">
          <button class="nav-link active" id="runs-tab" data-bs-toggle="tab" data-bs-target="#runs" type="button">My Runs</button>
        </li>
        <li class="nav-item">
          <button class="nav-link" id="requests-tab" data-bs-toggle="tab" data-bs-target="#requests" type="button">My Pending Requests</button>
        </li>
      </ul>
    <%# </div> %>


        <%# Cards of runs created %>
    <div class="tab-content" id="dashboardTabContent">
      <div class="tab-pane fade show active" id="runs">
        <div class="runs-created">
          <% @runs.each do |run| %>
            <% if run.user == current_user %>
              <%= render "runs/card_run", run: run %>
            <% end %>
          <% end %>
          <% if @past_runs.count != 0 %>
            <h2 class="title-dashboard mt-3 mb-4 text-center">Past Runs</h2>
            <% @past_runs.each do |run| %>
              <% if run.user == current_user %>
                <%= render "runs/card_run", run: run %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>

      <div class="tab-pane fade show active" id="requests">
        <%# Cards with requests made from others %>
        <% @pending_attendances.each do |attendance| %>
          <% if attendance.status == "pending"%>
            <%= render "attendances/card_attendance", attendance: attendance %>
          <% end %>
        <% end %>
      </div>
    </div>

     <%# attendance.run.user != current_user  %>




    <%# Cards with stats %>
    <div class="runs-stats">
      <div class="stats-card">
      </div>
    </div>


  </div>
</div>

app/views/pages/home.html.erb
<div class="wrapper"> <%# correspond au wrapper %>
  <%# <h1 class="logo-name">RunMate</h1> %>
  <%= image_tag "new_logo_white.png", alt:"Runmate", class: "logo-name"%>
  <div class="d-flex justify-content-center">
  </div>
  <div class="text-box d-flex flex-column align-items-center">
    <h2 class="home-title">Find your new mates</h2>
    <p class="home-text">Those who will help you run better,<br>smarter, faster.</p>
  </div>

  <div class="d-flex justify-content-center">
    <%= link_to "JOIN THE NEXT RUN", runs_path, class:"btn-home"%>
  </div>
</div>

app/views/pages/notifications.html.erb
<div class="container">
  <div class="notifications">
    <%= link_to :back, class:"text-decoration-none" do %>
      <span class="btn-back"><i class="fa-solid fa-circle-arrow-left fs-5 btn-back-blue me-1"></i>BACK</span>
    <% end %>
    <% if @notifications_for_attendances.count == 0 %>
      <h3 class="notifications-number">0 notifications</h3>
    <% else %>
      <h3 class="notifications-number"><%= pluralize(@current_user.unread_notifications_count, 'new notification')%></h3>
      <% @notifications_for_attendances.order(created_at: :desc).each do |notification| %>
        <span class="notifications-date <%= "notification-old" if notification.read %>"><%= notification.created_at.strftime("%I:%M %p")%></span>
        <%= render "notification_card", notification: notification %>
      <% end %>
    <% end %>
  </div>
</div>