config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: "pages#home"

  get '/dashboard', to: 'pages#dashboard'

  get '/chatrooms', to: 'pages#chatrooms'

  get '/notifications', to: 'pages#notifications'

  devise_scope :user do
    get '/users/profile', to: 'users/sessions#show', as: 'user_profile'
    get '/users/:id/edit', to: 'users/sessions#edit', as: 'edit_user'
    patch '/users/:id/edit', to: 'users/sessions#update', as: 'update_user'
    get '/users/:id/profile', to: 'users/sessions#show', as: 'profile'
  end

  get 'runs/map', to: "runs#map", as: :map

  resources :runs do
    resources :attendances, only: %i[new create]
    resources :messages, only: :create
    member do
      get 'chatroom', to: "runs#chatroom"
    end
  end

  resources :attendances, only: %i[index show update destroy] do
    resources :reviews, only: %i[new create] # routes Reviews
    member do
      patch 'confirm', to: "attendances#confirm"
      patch 'decline', to: "attendances#decline"
    end
  end
end

app/models/run.rb
class Run < ApplicationRecord
  CATEGORIES = ["Casual", "Coaching", "City Tour", "Hiking", "Running", "Trail Running", "Urban Trail"]
  # LEVEL = [1, 2, 3, 4, 5]
  belongs_to :user
  has_many :attendances, dependent: :destroy
  has_many :users, through: :attendances
  has_many :reviews
  has_many :messages, dependent: :destroy
  has_many :notifications, through: :messages
  geocoded_by :meeting_point
  after_validation :geocode, if: :will_save_change_to_meeting_point?
  has_one_attached :photo

  validates :category, inclusion: { in: CATEGORIES }
  # validates :level, inclusion: { in: LEVEL }

  after_create :create_first_attendee

  include PgSearch::Model
  pg_search_scope :search_by_address, against: [:meeting_point], using: { trigram: { threshold: 0.2 } }

  def city
    Geocoder.search([latitude, longitude]).first.city
  end

  private

  def create_first_attendee
    Attendance.create(user_id: self.user_id, run_id: self.id, status: 'confirmed')
  end

end

app/controllers/runs_controller.rb
require 'open-uri'
require 'json'

class RunsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show map]
  before_action :set_run, only: %i[show edit update destroy chatroom weather]

  def index
    if params[:query].present? || params[:start_date].present? || params[:hour].present?
      search
    else
      @runs = Run.where('date > ?', DateTime.now).order(date: :desc)
    end
    markers
  end

  def markers
    @runs = Run.where(id: @runs.map(&:id))
    @markers = @runs.geocoded.map do |run|
      {
        lat: run.latitude,
        lng: run.longitude,
        run_info_map_html: render_to_string(partial: "run_info_map", locals: { run: run }),
        run_marker_html: render_to_string(partial: "run_marker", locals: { run: run })
      }
    end
  end

  def search
    @runs = Run.where('date > ?', DateTime.now)

    # only one time zone is considered in this search
    Time.zone = "Europe/Paris"

    t = Time.zone.parse(params[:hour]) || Time.zone.parse("00:00")

    params[:start_date].present? ? d1 = Time.zone.parse(params[:start_date]).to_date : d1 = Time.now.to_date
    params[:end_date].present? ? d2 = Time.zone.parse(params[:end_date]).to_date : d2 = d1 + 5
    d2 = d1 + 1 if d2 == d1

    d1 = Time.zone.parse("#{d1.strftime('%F')} #{t.strftime('%T')}")
    d2 = Time.zone.parse("#{d2.strftime('%F')} #{t.strftime('%T')}")

    time_added = Time.parse("02:00:00").seconds_since_midnight.seconds
    d2 += time_added

    if params[:query].present?
      @runs = @runs.select { |run| (d1..d2).cover?(run.date) } if params[:date_start].present?

      @runs = @runs.near(params[:query], 10, units: :km, order: :distance)
                   .reverse_order

    elsif params[:start_date].present? || params[:hour].present?
      @runs = @runs.select { |run| (d1..d2).cover?(run.date) }
    else
      @runs = []
    end
  end

  def show
    @marker =
      [{
        lat: @run.geocode[0],
        lng: @run.geocode[1],
        run_info_smallmap_html: render_to_string(partial: "run_info_smallmap", locals: { run: @run }),
        run_marker_html: render_to_string(partial: "run_marker", locals: { run: @run })
      }]
    authorize @run
    @confirmed_users = @run.users.where(attendances: { status: "confirmed" })
    weather
  end

  def new
    @run = Run.new
    authorize @run
  end

  def create
    @run = Run.new(run_params)
    @run.user = current_user
    @run.level = params[:run][:level].last.to_i
    attach_photo
    authorize @run
    if @run.save
      redirect_to dashboard_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @run
  end

  def update
    authorize @run
    if @run.update(run_params)
      redirect_to run_path(@run), notice: 'Your run was successfully updated'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @run
    @run.destroy
    redirect_to runs_path, status: :see_other
  end

  def chatroom
    @message = Message.new
    authorize @run
  end

  def weather
    payload = URI.open("https://api.openweathermap.org/data/2.5/forecast?lat=#{@run.latitude}&lon=#{@run.longitude}&appid=#{ENV['OPENWEATHER_KEY']}&units=metric").read
    # data = JSON.parse(payload)["list"].find { |hash| hash["dt"] == @run.date.change({hour: (@run.date.hour / 3.0).ceil * 3 }).to_i }
    data = JSON.parse(payload)["list"].find { |hash| hash["dt"] == ((@run.date).to_i / 10800.0).ceil * 10800 }
    if data.nil?
      "no data available"
    else
      @temp = data["main"]["temp"]
      @weather = data["weather"][0]["main"]
      @icon = data["weather"][0]["icon"]
    end
  end

  # def map
  #   @runs = Run.all
  #   @markers = @runs.geocoded.map do |run|
  #     {
  #       lat: run.latitude,
  #       lng: run.longitude,
  #       run_info_map_html: render_to_string(partial: "run_info_map", locals: { run: run })
  #     }
  #   end
  #   authorize @runs
  # end

  private

  def set_run
    @run = Run.find(params[:id])
  end

  def run_params
    params.required(:run).permit(:name, :description, :category, :level, :distance, :max_person, :meeting_point, :date, :circuit)
  end

  def attach_photo
    case
    when @run.category == "Casual"
      file = File.open("app/assets/images/run_images/Casual.jpg")
    when @run.category == "Coaching"
      file = File.open("app/assets/images/run_images/Coaching.jpg")
    when @run.category == "City Tour"
      file = File.open("app/assets/images/run_images/City_tour.jpg")
    when @run.category == "Hiking"
      file = File.open("app/assets/images/run_images/Hiking.jpg")
    when @run.category == "Running"
      file = File.open("app/assets/images/run_images/Running.jpg")
    when @run.category == "Trail Running"
      file = File.open("app/assets/images/run_images/Trail_running.jpg")
    when @run.category == "Urban Trail"
      file = File.open("app/assets/images/run_images/Urban_trail.jpg")
    end
    @run.photo.attach(io: file, filename: "image.png", content_type: "image/png")
  end
end

app/views/runs/_card_run.html.erb
<div class="card-run">
  <%= link_to "", run_path(run), class:"card-run-link" %>
  <% if run.photo.attached? %>
    <%= cl_image_tag run.photo.key, class: "card-run-image"%>
  <% else %>
    <%= image_tag "cover.png", alt:"Runmate", class: "card-run-image"%>
  <% end %>
  <div class="card-run-content d-flex flex-column p-3">
      <h4 class="card-run-title"><%= run.name %></h4>
      <p class="calendar"><i class="fa-regular fa-calendar"></i><%=run.date.strftime("%b %e, %l:%M %p")%></p>
      <p><i class="fa-solid fa-location-dot"></i><em><%=run.meeting_point%></em></p>

    <div class="card-run-content-bottom d-flex justify-content-between align-items-center mt-3">
      <span class="category"> <%=run.category%></span>
      <div class="d-flex justify-content-between">
        <p class="m-0 fs-6 pe-3"><i class="fa-solid fa-gauge-high"></i> <%= run.level %>/5</p>
        <p class="m-0 fs-6"><i class="fa-solid fa-user"></i><%= run.users.where(attendances: { status: "confirmed" }).count %>/<%= run.max_person %></p>
      </div>
    </div>
  </div>
</div>

app/views/runs/_form.html.erb
<div class="form-container", data-controller="form-range">
  <%= simple_form_for run do |f| %>
    <%= f.input :name, placeholder: "Enter a name for your run", label: false %>
    <%= f.input :description, placeholder: "Write a short description", label: false %>
    <%= f.input :category, as: :radio_buttons, collection_wrapper_tag: "div", collection_wrapper_class: 'category-wrapper', item_wrapper_class: 'category-item', input_html: {class: 'category-selector'}, collection: Run::CATEGORIES, label: "Choose a category for the run:" %>
    <%= f.input :level, as: :check_boxes, collection: 1..5, label: "What is the level of difficulty?", id: "level", input_html: { class: "tag-selector" }, item_wrapper_class: 'tag-item' %>
    <div class="range-input-container">
      <%= f.input :distance, as: :range, label: "How many km will you run? (min: 5km)", wrapper_html: { class: 'm-0' }, input_html: { min: 5, max: 50, step: 1, class: "range-input", data: { form_range_target: "valueKm", action: "input->form-range#changeKm" }} %>
      <span class="value" data-form-range-target="labelKm">28</span>
    </div>
    <%= f.input :date, label: "When is the run?", html5: true, input_html: { data: {controller: "datetime-input"}} %>
    <div class="range-input-container">
      <%= f.input :max_person, as: :range, label: "How many people can join?", input_html: { min: 1, max: 20, step: 1, class: "range-input", data: { form_range_target: "valuePeople", action: "input->form-range#changePeople" }} %>
      <span class="value" data-form-range-target="labelPeople">11</span>
    </div>
    <%= f.input :meeting_point, placeholder: "Where are you all meeting?", label: false %>
    <%= f.submit class: "btn btn-outline-primary mt-2" %>
  <% end %>
</div>

<%# Time.now.strftime("%Y-%m-%d") %>

app/views/runs/_run_info_map.html.erb
<%= link_to "", run_path(run), class:"card-run-map-link" %>
<% case run.category %>
  <% when "Running" %>
  <%= image_tag "picto/running.png", class:"card-run-map-picto" %>
  <% when "Casual" %>
  <%= image_tag "picto/casual.png", class:"card-run-map-picto" %>
  <% when "Trail Running" %>
  <%= image_tag "picto/trail_running.png", class:"card-run-map-picto" %>
  <% when "Urban Trail" %>
  <%= image_tag "picto/trail_running.png", class:"card-run-map-picto" %>
  <% when "City Tour" %>
  <%= image_tag "picto/city_tour.png", class:"card-run-map-picto" %>
  <% when "Hiking" %>
  <%= image_tag "picto/hiking.png", class:"card-run-map-picto" %>
  <% when "Coaching" %>
  <%= image_tag "picto/coaching.png", class:"card-run-map-picto" %>
<% end %>
<% if run.photo.attached? %>
  <%= cl_image_tag run.photo.key, class: "card-run-map-image"%>
<% else %>
  <%= image_tag "cover.png", alt:"Runmate", class: "card-run-image"%>
<% end %>
<div class="card-run-map-content d-flex flex-column p-2">
    <h4 class="card-run-map-title"><%= run.name %></h4>
    <p class="calendar"><i class="fa-regular fa-calendar"></i><%=run.date.strftime("%b %e, %l:%M %p")%></p>
    <p><i class="fa-solid fa-location-dot"></i><em><%=run.meeting_point%></em></p>

  <div class="card-run-map-content-bottom d-flex justify-content-between align-items-center mt-3">
    <span class="category"> <%=run.category%></span>
    <div class="d-flex justify-content-between">
      <p class="m-0 fs-6 pe-3"><i class="fa-solid fa-gauge-high"></i> <%= run.level %>/5</p>
      <p class="m-0 fs-6"><i class="fa-solid fa-user"></i><%= run.users.where(attendances: { status: "confirmed" }).count %>/<%= run.max_person %></p>
    </div>
  </div>
</div>

app/views/runs/_run_info_smallmap.html.erb
<div class="small-map-card-run">
   <h6><%= @run.meeting_point %></h6>
</div>

app/views/runs/_run_marker.html.erb
<% case run.category %>
    <% when "Running" %>
    <%= image_tag "picto/running.png", class:"run-marker" %>
    <% when "Casual" %>
    <%= image_tag "picto/casual.png", class:"run-marker" %>
    <% when "Trail Running" %>
    <%= image_tag "picto/trail_running.png", class:"run-marker" %>
        <% when "Urban Trail" %>
    <%= image_tag "picto/trail_running.png", class:"run-marker" %>
    <% when "City Tour" %>
    <%= image_tag "picto/city_tour.png", class:"run-marker" %>
    <% when "Hiking" %>
    <%= image_tag "picto/hiking.png", class:"run-marker" %>
    <% when "Coaching" %>
    <%= image_tag "picto/coaching.png", class:"run-marker" %>
  <% end %>

app/views/runs/_search_bar.html.erb
<button class="btn btn-primary mt-4 btn-filter" data-bs-toggle="collapse" href="#collapseSearch" role="button" aria-expanded="false" aria-controls="collapseSearch">
  <i class="fa-solid fa-magnifying-glass me-1"></i> Filter
</button>
<div class="collapse" id="collapseSearch">
  <div id="searchBar" class="my-4" >
    <%= form_with url: runs_path, method: :get do |f| %>
      <div data-controller="address-autocomplete" data-address-autocomplete-api-key-value="<%= ENV["MAPBOX_API_KEY"]%>">
        <%= f.text_field :address,
          { data: { address_autocomplete_target: "address" },
          class:"d-none", placeholder: "Search Address" } %>
      </div>

      <div class="secondline d-flex py-2 justify-content-between" data-controller="flatpickr" data-address-autocomplete-target="dates">
        <div class="w-100">
          <%= f.text_field :start_date, {data: {flatpickr_target: 'startDateInput'}, class:"searchinput", placeholder: "Add dates" } %>
          <%= f.text_field :end_date, {data: {flatpickr_target: 'endDateInput'} , class: "d-none", placeholder: "Add dates"} %>
        </div>
        <div class="w-100">
          <%= f.time_field :hour , class: "searchinput" %>
        </div>
        <%= submit_tag "Find a run", class:"btn btn-primary btn-filter" %>
      </div>
    <% end %>
  </div>
</div>

app/views/runs/chatroom.html.erb
<div class="back-link-box", style="padding-top: 75px">
  <%= link_to :back, class:"back-link-chat" do %>
    <span class="btn-back fs-6"><i class="fa-solid fa-circle-arrow-left fs-6 btn-back-blue me-1"></i>BACK</span>
  <% end %>
</div>
<div class="container-chatroom"
  data-controller="run-subscription"
  data-run-subscription-run-id-value="<%= @run.id %>"
  data-run-subscription-user-id-value=" <%= current_user.id %> ">
    <h1 class="title-chatroom">#<%= @run.name %></h1>
    <div class="messages" data-run-subscription-target="messages">
      <% @run.messages.each do |message| %>
        <%= render "messages/message", message: message %>
      <% end %>
    </div>

    <div class="message-input">
      <%= simple_form_for [@run, @message],
      html: { data: { action: "turbo:submit-end->run-subscription#resetForm" }, class: "d-flex" } do |f| %>
        <%= f.input :content,
          label: false,
          placeholder: "Message ##{@run.name}",
          wrapper_html: {class: "flex-grow-1"} %>
        <%= f.submit "Send", class: "btn-send" %>
      <% end %>
    </div>
</div>

app/views/runs/edit.html.erb
<div class="container my-4", style="padding-top: 60px">
  <h1 class="my-3">EDIT YOUR RUN</h1>
  <%= render 'form', run: @run %>
</div>
<%= render "shared/navbar" %>

app/views/runs/index.html.erb
<div class="container mb-5", style="padding-top: 60px">

    <%# Search bar Partial %>
    <%= render "search_bar"%>
    <%# **** %>

  <% if params[:query].present? || params[:start_date].present? || params[:hour].present? %>
    <h1 class="title-index mt-3 text-left"><%= pluralize(@runs.count, 'Run') %> found</h1>
    <% else %>
    <h1 class="title-index mt-3 text-left">Find your next run</h1>
  <% end %>
  <a id="map-button" class="btn-sign-up d-flex align-items-center" data-bs-toggle="offcanvas" data-bs-target="#offcanvasLeft" aria-controls="offcanvasLeft">
    <p class="m-0">Show map</p>
    <i class="fa-sharp fa-solid fa-map-location-dot m-1"></i>
  </a>
  <div class="cards">
    <% @runs.each do |run| %>
      <%= render "card_run", run: run %>
    <% end %>
  </div>
</div>

<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasLeft" aria-labelledby="offcanvasLeftLabel" data-bs-backdrop="false">
  <div class="map"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    <button type="button" class="btn-close text-black fs-2" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
</div>

app/views/runs/map.html.erb
<div class="container p-3">
  <%= link_to :back, class:"text-decoration-none" do %>
    <span class="btn-back fs-6"><i class="fa-solid fa-circle-arrow-left fs-6 btn-back-blue me-1 mb-3"></i>BACK</span>
  <% end %>
  <div style="width: 100%; height: 75vh;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>
</div>

app/views/runs/new.html.erb
<div class="container my-4 px-3", style="padding-top: 60px">
  <div class="top-div d-flex justify-content-between align-items-center mb-3">
    <%= link_to :back do %>
      <i class="fa-solid fa-circle-arrow-left fs-5 btn-back-blue"></i>
    <% end %>
    <h1 class="mb-0">CREATE A NEW RUN</h1>
  </div>
  <%= render 'form', run: @run %>
</div>

app/views/runs/show.html.erb
<div class="show container" style="padding-top: 60px; padding-bottom: 70px">
  <%# Back button %>
  <div class="d-flex mt-4">
      <div class="btn-back">
        <%= link_to :back, class:"d-flex me-4 mt-2 text-decoration-none" do%>
          <i class="fa-solid fa-circle-arrow-left fs-5 btn-back-blue"></i>
        <% end %>
      </div>
      <h1 class="blue-title-show"><%= @run.name %></h1>
  </div>

  <%# Leader avatar and rating %>
  <div class="run-leader d-flex align-items-center mb-2">
      <%= link_to profile_path(@run.user), class:"text-decoration-none" do %>
        <%= cl_image_tag @run.user.photo.key %>
      <% end %>
      <div class="run-leader-info pt-3">
        <%= link_to profile_path(@run.user), class:"text-decoration-none" do %>
          <h4><%= @run.user.username.capitalize %></h4>
        <% end %>
        <ul class="stars list-inline">
        <% if @run.user.reviews.empty? %>
          <p> </p>
        <% else %>
          <% @run.user.reviews.average(:rating).round.times do %>
            <li class="list-inline-item"><i class="fa-solid fa-star"></i></li>
          <% end %>
        <% end %>
        </ul>
        <% if @run.user.reviews.empty? %>
          <p></p>
        <% else %>
          <p class="m-0"><%= (@run.user.reviews.average(:rating)*10).round / 10.0 %>/5</p>
        <% end %>
      </div>
  </div>

  <%# Buttons edit and delete %>
  <div class="d-flex justify-content-between px-3 mb-2">
      <% if user_signed_in? %>
        <% if @run.user == current_user %>
          <%= link_to edit_run_path, class: 'text-decoration-none' do %>
            <span class="btn-edits"><i class="fa-regular fa-pen-to-square me-1"></i>Edit your run</span>
          <% end %>
          <%= link_to run_path(@run), class: 'text-decoration-none', data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
            <span class="btn-edits"><i class="fa-regular fa-trash-can me-1"></i>Delete the run</span>
          <% end %>
        <% end %>
      <% end %>
  </div>

  <%# Image of the run %>
  <% if @run.photo.attached? %>
    <div class="run-image mb-3" style="background-image: url('<%= cl_image_path @run.photo.key %>')">
  <% else %>
    <div class="run-image mb-3" style="background-image: url(<%= asset_path "cover.png" %>)">
  <% end %>
    <div class="run-image-info mb-3">
        <span class="category-run"><%= @run.category %></span>
        <span><%= @run.city %></span>
    </div>
    </div>

  <%# Stats %>
  <div class="run-specs mb-3">
      <div class="violet-square">
        <p>RunMates</p>
        <p><i class="fa-solid fa-user"></i><%= @confirmed_users.count %>/<%= @run.max_person %></p>
      </div>
      <div class="violet-square">
        <p>Distance</p>
        <p><%= @run.distance %> km</p>
      </div>
      <div class="violet-square">
        <p>Level</p>
        <p><i class="fa-solid fa-gauge-high"></i><%= @run.level %>/5</p>
      </div>
  </div>

  <%# Infos of the run %>
  <div class="run-infos mb-3">
      <div class="run-date mb-3">
        <p class="me-1"><i class="fa-solid fa-calendar-days"></i><%= @run.date.strftime("%A, %b %d") %></p>
        <p><i class="fa-solid fa-clock"></i><%= @run.date.strftime("%I:%M %p") %></p>
      </div>
      <div class="run-description">
        <p><%= @run.description %></p>
        <p class="address"><i class="fa-solid fa-location-dot"></i><%= @run.meeting_point %></p>
      </div>
    <%# MAP %>
      <div style="width: 100%; height: 20vh;"
      data-controller="smallmap"
      data-smallmap-markers-value="<%= @marker.to_json %>"
      data-smallmap-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
  </div>

  <%# Join the run button %>
  <% unless @confirmed_users.include?(current_user) %>
    <%= link_to "Join the run", new_run_attendance_path(@run), class:"join-button"%>
  <% end %>

  <%# Weather forecast %>
  <div class="weather mb-3 py-2">
      <h3>Weather Forecast</h3>
      <div class="run-weather d-flex justify-content-around align-items-center">
        <% if @temp.nil? %>
          <p class="no-data"><em>Weather Forecast is available 5 days before the run</em></p>
        <% else %>
          <p><%= @weather %></p>
          <p><%= @temp.round(1) %>°C</p>
          <%= image_tag("https://openweathermap.org/img/w/#{@icon}.png") %>
        <% end %>
      </div>
  </div>

  <%# List of attendants %>
  <div class="attendants mt-5">
    <h3>They already joined the run:</h3>
    <% @confirmed_users.each do |user| %>
      <%= link_to profile_path(user), class:"text-decoration-none" do %>
      <div class="attendant d-flex align-items-end">
            <%= cl_image_tag user.photo.key %>
            <div class="attendant-info">
              <p><%= user.username.capitalize %></p>
              <p>RunMate since <%= user.created_at.strftime("%B %Y") %></p>
            </div>
      </div>
        <% end %>
      <% end %>

    <%# Link to the chatroom %>
    <div class="chatroom-link">
        <% if @confirmed_users.include?(current_user) %>
          <%= link_to "Chat with your Mates", chatroom_run_path(@run), class:"btn btn-outline-primary mt-1" %>
        <% end %>
    </div>
  </div>
</div>