config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: "pages#home"

  get '/dashboard', to: 'pages#dashboard'

  get '/chatrooms', to: 'pages#chatrooms'

  get '/notifications', to: 'pages#notifications'

  devise_scope :user do
    get '/users/profile', to: 'users/sessions#show', as: 'user_profile'
    get '/users/:id/edit', to: 'users/sessions#edit', as: 'edit_user'
    patch '/users/:id/edit', to: 'users/sessions#update', as: 'update_user'
    get '/users/:id/profile', to: 'users/sessions#show', as: 'profile'
  end

  get 'runs/map', to: "runs#map", as: :map

  resources :runs do
    resources :attendances, only: %i[new create]
    resources :messages, only: :create
    member do
      get 'chatroom', to: "runs#chatroom"
    end
  end

  resources :attendances, only: %i[index show update destroy] do
    resources :reviews, only: %i[new create] # routes Reviews
    member do
      patch 'confirm', to: "attendances#confirm"
      patch 'decline', to: "attendances#decline"
    end
  end
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :run
  has_many :messages, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_one :review, dependent: :destroy
end

# WE CAN USE THESE:
# run = Run.first
# run.attendances.confirmed

# run.attendances.first.pending?
# run.attendances.first.confirmed!

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def index
    @attendances = Attendance.all
  end

  def new
    @run = Run.find(params[:run_id])
    @attendance = Attendance.new
    authorize @attendance
  end

  def create
    @run = Run.find(params[:run_id])
    @user = current_user
    @attendance = Attendance.new(attendance_params)
    @attendance.user = @user
    @attendance.run = @run
    authorize @attendance
    if @attendance.save
      Notification.create(user: @attendance.run.user, attendance: @attendance)
      NotificationsChannel.broadcast_to(
        @attendance.run.user, @attendance.run.user.unread_notifications_count)
      redirect_to run_path(@run)
    else
      redirect_to run_path(@run), status: :unprocessable_entity
    end
  end

  def destroy
    @attendance = Attendance.find(params[:id])
    authorize @attendance
    @attendance.destroy
    redirect_to attendances_path
  end

  def confirm
    @attendance = Attendance.find(params[:id])
    @attendance.status = "confirmed"
    authorize @attendance
    @attendance.save
    Notification.create(user: @attendance.user, attendance: @attendance)
    NotificationsChannel.broadcast_to(
      @attendance.user, @attendance.user.unread_notifications_count)
    redirect_to dashboard_path
  end

  def decline
    @attendance = Attendance.find(params[:id])
    @attendance.status = "declined"
    authorize @attendance
    @attendance.save
    Notification.create(user: @attendance.user, attendance: @attendance)
    NotificationsChannel.broadcast_to(
      @attendance.user, @attendance.user.unread_notifications_count)
    redirect_to dashboard_path
  end

  private

  def attendance_params
    params.require(:attendance).permit(:content, :status)
  end
end

app/views/attendances/_card_attendance.html.erb
<div class="card-attendance-request p-3">
  <%= link_to "", run_path(attendance.run), class:"card-run-link" %>
  <div class="card-attendance-content-top d-flex flex-start justify-content-between align-items-center mb-3">
    <%= cl_image_tag attendance.run.photo.key %>
    <h4 class="card-attendance-title"><%= attendance.run.name %> </h4>

  </div>
  <p class="category"><i class="fa-regular fa-calendar"></i>  | <%= attendance.run.date.strftime("%b %e, %l:%M %p") %> </p>
  <div class="message d-flex justify-content-start">
    <% if attendance.user != current_user %>
    <p><i class="fa-solid fa-user"></i>  | Request made by:</p>
    <p class="ms-2"><%= attendance.user.username %></p>
    <% else %>
    <p><i class="fa-solid fa-user"></i>  | Request sent to:</p>
    <p class="ms-2"><%= attendance.run.user.username %></p>
    <% end %>
  </div>
  <div class="message d-flex justify-content-start">
    <p><i class="fa-regular fa-envelope-open"></i>  | Message:</p>
    <p class="ms-2">"<em><%= attendance.content %></em>"</p>
  </div>
  <p>Status: <strong><%= attendance.status.capitalize %></strong></p>
  <% if attendance.run.user == current_user %>
    <div class="d-flex flex-start align-items-center">
      <%= link_to decline_attendance_path(attendance), class: "btn-delete fs-3 p-2 action", data: { turbo_method: :patch } do %>
        <i class="fa-solid fa-thumbs-down"></i>
      <% end %>
      <% if attendance.status != "confirmed" %>
        <%= link_to confirm_attendance_path(attendance), class: "btn-delete fs-3 p-2 action", data: { turbo_method: :patch } do %>
          <i class="fa-solid fa-thumbs-up"></i>
        <% end %>
      <% end %>
    </div>
  <% end %>
    <div class="d-flex justify-content-end">
      <% if attendance.user == current_user && attendance.run.date > DateTime.now %>
        <%= link_to attendance_path(attendance), class: "btn-delete fs-5 action text-danger", data: { turbo_method: :delete,turbo_confirm: "Are you sure?" } do %>
          <i class="fa-regular fa-trash-can"></i>
        <% end %>
      <% end %>
    </div>
    <% if attendance.run.date < DateTime.now && attendance.status == "confirmed" %>
      <%= link_to new_attendance_review_path(attendance), class: "action" do %>
      <p class="add-a-review"><i class="fa-solid fa-plus me-2"></i>Add a review</p>
      <% end %>
    <% end %>
</div>

app/views/attendances/index.html.erb
<div class="body-attendances">
  <div class="container mt-2 mb-4", style="padding-top: 60px">
    <%= link_to :back, class:"text-decoration-none" do %>
      <span class="btn-back"><i class="fa-solid fa-circle-arrow-left fs-5 btn-back-blue me-1"></i>BACK</span>
    <% end %>
    <h1 class="title-dashboard my-4 text-center">YOUR REQUESTS</h1>
    <div class="d-flex flex-column">
        <% @attendances.each do |attendance| %>
          <% if attendance.user == current_user && attendance.run.user != current_user %>
            <%= render "card_attendance", attendance: attendance %>
          <% end %>
        <% end %>
    </div>
  </div>
</div>

app/views/attendances/new.html.erb
<div class="container mt-4", style="padding-top: 60px">
  <div class="row justify-content-center">
    <div class="col-xs-12 col-sm-4">
      <%= link_to :back, class:"text-decoration-none" do %>
        <span class="btn-back fs-6"><i class="fa-solid fa-circle-arrow-left fs-6 btn-back-blue me-1"></i>BACK</span>
      <% end %>
    <div class="form-box mt-3">
        <h1 class="devise-title">You want to join this run?</h1>
        <%= simple_form_for [@run, @attendance] do |f| %>
          <%= f.input :content, placeholder: "Your message...", label: "Send a quick message to the organizer !", label_html: { class: "my-3"} %>
          <div class="d-flex justify-content-center">
            <%= f.submit "Ask to join", class: "btn btn-outline-primary mt-3" %>
          </div>
        <% end %>
    </div>
    </div>
  </div>
</div>